#pragma once

#ifndef DEFINES_COMMANDS_CODES_HPP
#define DEFINES_COMMANDS_CODES_HPP

#define INTER_COMMAND_HELP 100

#define INTER_COMMAND_SETTINGS 200
	#define INTER_COMMAND_SETTINGS_SHOW 210
		#define INTER_COMMAND_SETTINGS_SHOW_DEFAULT 211
		#define INTER_COMMAND_SETTINGS_SHOW_ALL 212
		#define INTER_COMMAND_SETTINGS_SHOW_CONSOLE 213
		#define INTER_COMMAND_SETTINGS_SHOW_FREEGLUT 214
	#define INTER_COMMAND_SETTINGS_SAVE 220
	#define INTER_COMMAND_SETTINGS_GET 230

#define INTER_COMMAND_SET 300
	#define INTER_COMMAND_SET_FOLDERPATH 301
	#define INTER_COMMAND_SET_FILEPATH 302
	#define INTER_COMMAND_SET_FILENUMBER 303
#define INTER_COMMAND_UNSET 400


#define INTER_COMMAND_CONVERT 500
#define INTER_COMMAND_VISUALIZE 600
#define INTER_COMMAND_RESET 700
#define INTER_COMMAND_RESTART 800

#endif // !DEFINES_COMMANDS_CODES_HPP
