#pragma once

#ifndef DEFINES_COMMANDS_CODES_HPP
#define DEFINES_COMMANDS_CODES_HPP

#define INTER_COMMAND_HELP 100
#define INTER_COMMAND_SETTINGS 200
#define INTER_COMMAND_SET 300
#define INTER_COMMAND_CONVERT 400
#define INTER_COMMAND_VISUALIZE 500
#define INTER_COMMAND_RESET 600
#define INTER_COMMAND_RESTART 700

#endif // !DEFINES_COMMANDS_CODES_HPP
