#pragma once

#ifndef DEFINES_COMMANDS_CODES_HPP
#define DEFINES_COMMANDS_CODES_HPP

constexpr auto INTER_COMMAND_HELP = 100;
	constexpr auto INTER_COMMAND_HELP_SETTINGS = 101;
	constexpr auto INTER_COMMAND_HELP_SET = 102;
	constexpr auto INTER_COMMAND_HELP_UNSET = 103;
	constexpr auto INTER_COMMAND_HELP_CONVERT = 104;
	constexpr auto INTER_COMMAND_HELP_VISUALIZE = 105;
	constexpr auto INTER_COMMAND_HELP_RESET = 106;
	constexpr auto INTER_COMMAND_HELP_RESTART = 107;

constexpr auto INTER_COMMAND_SETTINGS = 200;
	constexpr auto INTER_COMMAND_SETTINGS_SHOW = 210;
		constexpr auto INTER_COMMAND_SETTINGS_SHOW_DEFAULT = 211;
		constexpr auto INTER_COMMAND_SETTINGS_SHOW_ALL = 212;
		constexpr auto INTER_COMMAND_SETTINGS_SHOW_CONSOLE = 213;
		constexpr auto INTER_COMMAND_SETTINGS_SHOW_FREEGLUT = 214;
	constexpr auto INTER_COMMAND_SETTINGS_SAVE = 220;
	constexpr auto INTER_COMMAND_SETTINGS_GET = 230;
	constexpr auto INTER_COMMAND_SETTINGS_RESET = 240;

constexpr auto INTER_COMMAND_SET = 300;
	constexpr auto INTER_COMMAND_SET_FOLDERPATH = 301;
	constexpr auto INTER_COMMAND_SET_FILEPATH = 302;
	constexpr auto INTER_COMMAND_SET_FILENUMBER = 303;
	constexpr auto INTER_COMMAND_SET_SPININDEX = 304;
	constexpr auto INTER_COMMAND_SET_SETTINGSFOLDER = 305;
	constexpr auto INTER_COMMAND_SET_SETTINGSFILE = 306;
	constexpr auto INTER_COMMAND_SET_COLORING = 307;
	constexpr auto INTER_COMMAND_SET_BACKGROUNDCOLOR = 308;
	constexpr auto INTER_COMMAND_SET_FULLSCREEN = 309;
	constexpr auto INTER_COMMAND_SET_SHAPE = 310;
	constexpr auto INTER_COMMAND_SET_TRANSLATION_BY_ELEMENT = 311;
	constexpr auto INTER_COMMAND_SET_ESTRANGEMENT_CHANGES = 312;
	constexpr auto INTER_COMMAND_SET_SCALING_CHANGES = 313;
	constexpr auto INTER_COMMAND_SET_TRANSLATION_CHANGES = 314;
	constexpr auto INTER_COMMAND_SET_CAMERA_CHANGES = 315;
	constexpr auto INTER_COMMAND_SET_SPINRATE = 316;
	constexpr auto INTER_COMMAND_SET_SUBWINDOWING = 317;
	constexpr auto INTER_COMMAND_SET_GAP = 318;
	constexpr auto INTER_COMMAND_SET_POLIGONRATE = 319;
	constexpr auto INTER_COMMAND_SET_LAYER = 320;
	constexpr auto INTER_COMMAND_SET_MATERIAL = 321;
	constexpr auto INTER_COMMAND_SET_MULTIMATERIAL = 322;
	constexpr auto INTER_COMMAND_SET_MULTILAYER = 323;
constexpr auto INTER_COMMAND_UNSET = 400;


constexpr auto INTER_COMMAND_CONVERT = 500;
	constexpr auto INTER_COMMAND_CONVERT_VAMPIRE5 = 510;


constexpr auto INTER_COMMAND_VISUALIZE = 600;
	constexpr auto INTER_COMMAND_VISUALIZE_FOLDER = 610;
	constexpr auto INTER_COMMAND_VISUALIZE_FILE = 620;




constexpr auto INTER_COMMAND_RESET = 700;

constexpr auto INTER_COMMAND_RESTART = 800;

#endif // !DEFINES_COMMANDS_CODES_HPP
